from Exceptions.Error import Error


class ValueIsNumber(Error):
    pass
